package org.jetbrains.plugins.scala.config.scalaProjectTemplate.ui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import org.jetbrains.plugins.scala.components.TypeAwareHighlightingApplicationState;

import javax.swing.*;
import java.awt.*;

/**
 * User: Dmitry Naydanov
 * Date: 11/12/12
 */
public class ScalaAdvancedModuleSettings {
    private JCheckBox enableTypeAwareHighlightingCheckBox;
    private JPanel mainPanel;

    public ScalaAdvancedModuleSettings() {
        boolean enableTypeAwareHighlighting = TypeAwareHighlightingApplicationState.getInstance().suggest();
        enableTypeAwareHighlightingCheckBox.setSelected(enableTypeAwareHighlighting);
    }

    public boolean isTypeAwareHighlightingEnabled() {
        return enableTypeAwareHighlightingCheckBox.isSelected();
    }

    public JComponent getComponent() {
        return mainPanel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        final Spacer spacer1 = new Spacer();
        mainPanel.add(spacer1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        enableTypeAwareHighlightingCheckBox = new JCheckBox();
        enableTypeAwareHighlightingCheckBox.setEnabled(true);
        enableTypeAwareHighlightingCheckBox.setSelected(false);
        enableTypeAwareHighlightingCheckBox.setText("Enable type-aware highlighting");
        mainPanel.add(enableTypeAwareHighlightingCheckBox, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
